### ISSUE TITLE
Error while setting up android

### ISSUE THREAD

**Issue by SafatB** [TeamNexus/issues#18] opened 2017-07-29 05:21 UTC
I installed the latest build of Nexus OS along with the complete installation of aroma gapps package from open gapps, however each time when I attempt to set up my device through wifi, it tells me that my device can't connect to the google server therefore making the device inaccessible after installing gapps. 

I finally got into my phone after removing the gapps through wiping the system partition but after multiple attempts at flashing gapps in my phone, it kept showing the same error in the setup wizard.

**Comment by Lukas0610** [comment] 2017-07-29 08:33
Bugreport? Logcat?

**Comment by SafatB** [comment] 2017-07-30 02:55
I couldn't get the bug report from the Nexus app as it wasn't opening and all I got was a black screen that caused my phone to freeze momentarily.

 The home button wasn't working too and the I could only get out of an app using the back and recent keys.

**Comment by Lukas0610** [comment] 2017-07-30 14:16
And what about a normal logcat using ADB?

**Comment by Lukas0610** [comment] 2017-08-07 12:47
Duplicate of #22

**Closed as completed by Lukas0610** 2017-08-07 12:47 UTC
