### ISSUE TITLE
NexusOS installation problem

### ISSUE THREAD

**Issue by janwendt** [TeamNexus/issues#20] opened 2017-07-30 09:39 UTC
After a clean flash it is not possible to import the backup from googles cloud. It tried it many times. 
It does not ask for username and password and only says:
"Couldn't sign in: There was a problem communicating with Google servers."

"Set up as new" does not work either. After selecting WLan it says "checking for updates" but nothing happens.

#### Device
Samsung Galaxy S6 SM-G925F

#### Used build
Latest: NexusOS-zero-multitarget-2017-07-29_1929.zip

**Comment by Lukas0610** [comment] 2017-07-30 14:16
Please append a bugreport from the TheNexus-App...

**Comment by janwendt** [comment] 2017-07-30 14:21
@Lukas0610 How can i append a bugreport when i can not install your ROM? :D

**Comment by Lukas0610** [comment] 2017-07-30 14:23
I'm very sure you can skip that setup, can you?

**Comment by janwendt** [comment] 2017-07-30 14:51
I can skip it but when i click "bugreport" in your app it never ends generating the report. I already created one a few weeks ago and it worked. Cant you reproduce it on your own device?

**Comment by Lukas0610** [comment] 2017-07-30 14:56
Generating a bugreport and (at least) adding another Google-accounts works fine for me (which does the same as adding the first account)

**Comment by janwendt** [comment] 2017-07-30 15:03
after a reboot the bugreport was visible: 
[NexusOS-2017-07-30_16-52-02.zip](https://github.com/TeamNexus/issues/files/1185761/NexusOS-2017-07-30_16-52-02.zip)

**Comment by janwendt** [comment] 2017-07-31 10:42
@Lukas0610 the last build which works without problems is:
NexusOS-zero-multitarget-2017-07-15_1546.zip
For all later builds I have the same problem as described above. I hope this information helps you.
I noticed during the setup of the device that it says "Willkommen bei deinem SM-G925F" and with the newer builds "Willkommen bei deinem SM-G920F". Maybe it does not recognize my S6 Edge correctly although the correct kernel was injected during the flash.

**Comment by jomjol** [comment] 2017-08-06 06:25
Problem is only present, if you install newest version brand new on a blank Galaxy S6.
Work around: 

1. install "NexusOS-zero-multitarget-2017-07-15_1546.zip"
2. setup Galaxy S6, 
3. Update with Nexus APP to newest version ... 2017_07_29

--> Google service are still working

**Comment by Lukas0610** [comment] 2017-08-07 12:46
Duplicate of #22

**Closed as completed by Lukas0610** 2017-08-07 12:46 UTC
