### ISSUE TITLE
Wi-fi turns off sometime after screen off 

### ISSUE THREAD

**Issue by zxcbnz** [TeamNexus/issues#23] opened 2017-08-07 17:41 UTC
#### Steps for a proper issue
Leave the phone until screen turns off. After an arbitrary amount of time (5-10 minutes, sometimes up to an hour) Wi-fi disconnects and connection will stay on with mobile data until screen is turned on. Wi-fi will then connect in a matter of 1.5-3 seconds.
May be a problem with OpenVPN and AFWall+. Also using Orbot for most applications.
After this happening too many times, I need to do a hard reboot, as OpenVPN errors out and I can't get through to the Internet without disabling AFWall.

The connection seems to drop ~2 minutes after this message:
`6188  6208 I art     : Background partial concurrent mark sweep GC freed 11955(693KB) AllocSpace objects, 27(988KB) LOS objects, 52% free, 1817KB/3MB, paused 5.909ms total 59.895ms`

All related applications have battery conservation disabled.

Follow with a couple more of these and the adb connection is dropped:
`4444  4507 I BatteryService: isUnlockingWithFingerprintAllowed(): nexus_no_critical_battery_shutdown=false`

I don't know if it's actually connecting to DropBox or not, but I'd like to turn that off if it is.
```
5348 I BootReceiver: Copying audit failures to DropBox
5348 I BootReceiver: Copied 0 worth of audits to DropBox
```
I thought we were removing all Google things?

```
5700  7922 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_DNS OK 39ms, connectivitycheck.gstatic.com=172.217.23.131
5700  7921 D NetworkMonitor/NetworkAgentInfo [WIFI () - 100]: PROBE_DNS OK 47ms, www.google.com=216.58.209.36

5700  5724 D GnssLocationProvider: SUPL_HOST=supl.google.com
5700  5724 D GnssLocationProvider: NTP_SERVER=north-america.pool.ntp.org
```

Lineage 22/7_0032 G920F 
I am using 22/7 build, as the later ones lag horribly on my device, including the latest Testing release. This issue is present on those as well.

[NexusOS-2017-08-07_18-56-40.zip](https://github.com/TeamNexus/issues/files/1205624/NexusOS-2017-08-07_18-56-40.zip)

**Comment by Lukas0610** [comment] 2017-08-07 17:52
From what I can see, the problem is caused by OpenVPN and/or AFWall, probably AFWall. Multiple commands related to the networking-system fail after AFWall executes multiple commands.

Maybe you can try to use mobile data only and turn the screen off afterwards, if I'm correct, the same problem should occur.

But for now, this issue is closed as **Caused by 3rd party**

**Closed as completed by Lukas0610** 2017-08-07 17:52 UTC

**Comment by zxcbnz** [comment] 2017-08-07 18:15
What about the Google/Dropbox stuff?

**Comment by Lukas0610** [comment] 2017-08-07 18:21
The first Google-stuff is, as it says, just a connectivity-test and the second one is GPS-connected and both can't be removed without causing possible issues with network-status and GPS.

And the Drop**B**ox-thing has nothing to with Drop**b**ox
